torpe/torpe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('tweet_crawl/',
    include('tweet_crawl.urls')),
    path('admin/', admin.site.urls),
]

torpe/tweet_crawl/urls.py
from django.urls import path

from . import views

app_name = 'tweet_crawl'

urlpatterns = [
    path('', views.index, name='index'),
    path('querie_list/', views.querie_list, name='querie_list'),
    path('querie/<int:querie_id>/', views.tweet_list, name='tweet_list'),
    path('querie/<int:querie_id>/analisys/', views.analisys, name='analisys'),
    path('tweet/<int:tweet_id>', views.tweet, name='tweet'),
    path('search', views.search, name='search'),
]

torpe/tweet_crawl/models.py
from .twapi import searchTweets
from django.db import models
from django.utils import timezone

class Querie(models.Model):
   
    entry = models.CharField(max_length = 200)
    start_day = models.DateField('data de inicio da consulta')
    end_day = models.DateField('data de termino da consulta')
    executed_on = models.DateField('data de execução da consulta', default=timezone.now())
    max_itens = models.IntegerField(default=0)
    rank_size = models.IntegerField(default=5)
    crawled_tweets = models.IntegerField(default=0)
    #Methods
    def __str__(self):
        return self.entry    

    def doTweetCrawling(self):  
        tweets_list = searchTweets(
            self.entry,
            self.start_day,
            self.end_day,
            10
        )
        tweets_amount = len(tweets_list)
        if (tweets_amount !=0):
            for tweet in tweets_list:
                new_tweet = Tweet(
                    id_str = tweet.id_str,
                    created_at = tweet.created_at,
                    created_by = tweet.author.id_str,
                    querie = self,
                    text = tweet.text
                )                    
                new_tweet.save()
            tweets_amount = len(tweets_list)
            self.crawled_tweets = tweets_amount
            self.save()
        return tweets_amount
'''
    def rankingTweetsTerms(self, tweets_list):
        bag_of_nouns = twapi.extractTweetsNouns(tweets_list)
        ranked_terms = twapi.rankingItems(bag_of_nouns)
        return ranked_terms
    
    def rankingTweetsEntities(self, tweets_list):
        bag_of_entities = twapi.identifyEntities(tweets_list)
        ranked_entities = twapi.rankingItems(bag_of_entities)
        return ranked_entities
    
    def plotPopulars(self, ranked_list, plot_title):
        plot = twapi.plotRanking(
            ranked_list, 
            self.rank_size, 
            plot_title
        )
        return plot
    
    def doFullAnalisys(self):
        return processFullWorkflow(
            self.querie_entry,
            self.start_day,
            self.end_day,
            self.rank_size
        )
      
'''

class Tweet(models.Model):
    id_str = models.CharField(max_length = 20)
    created_at = models.DateTimeField('data de criação do tweet')
    created_by = models.CharField(max_length = 10)
    querie = models.ForeignKey(Querie, on_delete=models.CASCADE)
    text = models.CharField(max_length=280)
    
    #Methods
    def __str__(self):
        return self.text

torpe/tweet_crawl/forms.py
from django.forms import ModelForm
from .models import Querie

class QuerieForm(ModelForm):
    class Meta:
        model = Querie
        fields = [ 'entry', 'start_day', 'end_day', 'rank_size' ]
        

torpe/tweet_crawl/views.py
from django.http import Http404, HttpResponse
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.utils import timezone as tz
from .models import Querie, Tweet
from .forms import QuerieForm
from django.template import loader

def index(request):

    form = QuerieForm()
    if ( request.method == 'POST'):
        form = QuerieForm(request.POST)
        if(form.is_valid()):
            querie_entry = form.cleaned_data['entry']
            querie_start_day = form.cleaned_data['start_day']
            querie_end_day = form.cleaned_data['end_day']
            querie_rank_size = form.cleaned_data['rank_size']
            new_querie = Querie(
                entry = querie_entry, 
                start_day = querie_start_day, 
                end_day = querie_end_day, 
                rank_size = querie_rank_size, 
                executed_on = tz.now()
            )            
            new_querie.save()            
            new_querie.doTweetCrawling()
            return redirect('tweet_crawl:querie_list')
    elif(request.method == 'GET'):
            
        return render(request, 'tweet_crawl/index.html', {'form':form})
    
def querie_list(request):
    queries =  Querie.objects.order_by('-executed_on')
    return render(request, 'tweet_crawl/querie_list.html', {'queries': queries})
    
def tweet_list(request, querie_id):
    querie = get_object_or_404(Querie, pk=querie_id)
    total = len(get_list_or_404(Tweet, querie=querie_id))
    return render(request, 'tweet_crawl/tweet_list.html', {'querie': querie, 'total': total })
    
def analisys(request, querie_id):
    
    response = 'analisys on %s querie'
    
    return HttpResponse(response % querie_id)

def search(request, querie_id):
    
    response = 'search on %s querie'
    
    return HttpResponse(response % querie_id)

    
def tweet(request, tweet_id):
    tweet = get_object_or_404(Tweet, pk=tweet_id)
    return render(request, 'tweet_crawl/tweet.html', {'tweet': tweet})

torpe/tweet_crawl/templates/tweet_crawl/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Torpe - Tweet Crawler</title>
  </head>
  <body>
      <h1>Torpe - Tweet Crawler</h1>
    <p>Just to made your own tweets dataset</p>
    <br>
    <br>
    <form action="." method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Go">
    </form>
  </body>
</html>

torpe/tweet_crawl/templates/tweet_crawl/querie_list.html
{% if queries %}
    <ul>
    {% for querie in queries %}
        <li>
        <a href="{% url 'tweet_crawl:tweet_list' querie.id %}">{{ querie.entry}}</a> 
        | {{querie.start_day}} 
        | {{querie.end_day}} 
        | {{querie.rank_size}} 
        | {{querie.executed_on}}
        | {{querie.crawled_tweets}}
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No queries are available.</p>
{% endif %}

torpe/tweet_crawl/templates/tweet_crawl/tweet_list.html
<h1>Querie Entry: {{querie.entry}}</h1>
<p>
    Performed on: {{querie.executed_on}} | from: {{querie.start_day}} | to: {{querie.end_day}}<br>
    
</p>

Has crawled {{ total }} tweets.
<br>
    {% if total != 0 %}
    <ul>
        {% for tweet in querie.tweet_set.all %}
        <li>
            <a href="{% url 'tweet_crawl:tweet' tweet.id %}">{{ tweet.id_str}}</a>
            | {{tweet.created_at}} 
            | {{tweet.created_by}} 
            | {{tweet.text}}
        </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>No tweets found.</p>
    {% endif %}